# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pscan < Formula
  desc ""
  homepage "https://github.com/Nelwhix/pScan"
  version "0.0.5"

  on_macos do
    url "https://github.com/Nelwhix/pScan/releases/download/v0.0.5/pScan_Darwin_all.tar.gz"
    sha256 "7dba1bf098a47e7de974bf23094729b06cbb7894a6e995220edcedf85bf836c9"

    def install
      bin.install "pScan"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Nelwhix/pScan/releases/download/v0.0.5/pScan_Linux_x86_64.tar.gz"
      sha256 "7dff65ca9f50cda566f52fbe986705202d6bc73180cda5a13f5753c5b6b0587e"

      def install
        bin.install "pscan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nelwhix/pScan/releases/download/v0.0.5/pScan_Linux_arm64.tar.gz"
      sha256 "42c3775a46aa42971752b24e7e62536a0bb9ef77f30ea100722d91e8ef8cf052"

      def install
        bin.install "pscan"
      end
    end
  end
end
