# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PScan < Formula
  desc ""
  homepage "https://github.com/Nelwhix/pScan"
  version "0.0.3"

  on_macos do
    url "https://github.com/Nelwhix/pScan/releases/download/v0.0.3/pScan_Darwin_all.tar.gz"
    sha256 "09516314458c9d21590d4723bd9aa8041be9a3112b2259e499231ee0e2c84adb"

    def install
      bin.install "pScan"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nelwhix/pScan/releases/download/v0.0.3/pScan_Linux_arm64.tar.gz"
      sha256 "bd28c2ca29052b5a16d7ea404e0b9b0fca7eb25aa87c285d0ac46b8c5386b41e"

      def install
        bin.install "pScan"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Nelwhix/pScan/releases/download/v0.0.3/pScan_Linux_x86_64.tar.gz"
      sha256 "fc0577bd29c50e6ac879b481fd52474b013bb4c52ec3762ecb2f6915f28df51a"

      def install
        bin.install "pScan"
      end
    end
  end
end
