# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pscan < Formula
  desc ""
  homepage "https://github.com/Nelwhix/pScan"
  version "0.0.4"

  on_macos do
    url "https://github.com/Nelwhix/pScan/releases/download/v0.0.4/pScan_Darwin_all.tar.gz"
    sha256 "4b766d133d970324ff7dfe09e389fbadc276ec9a98f3cd788747e201783339af"

    def install
      bin.install "pScan"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nelwhix/pScan/releases/download/v0.0.4/pScan_Linux_arm64.tar.gz"
      sha256 "b9f67b530879cbc45bcb94710a36e4abd651a9ab09ecd4fc26d72363d497647b"

      def install
        bin.install "pscan"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Nelwhix/pScan/releases/download/v0.0.4/pScan_Linux_x86_64.tar.gz"
      sha256 "cbb93a97403c9414e747387ad3f236dd827ee5606ec9158e8b41cdd43ea63375"

      def install
        bin.install "pscan"
      end
    end
  end
end
